# Generated by Django 4.0.1 on 2022-03-21 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('place', models.CharField(blank=True, max_length=45, null=True)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_category', to='category.category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenditure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
