# Generated by Django 4.0.1 on 2022-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='product',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
