# Generated by Django 4.0.1 on 2022-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_expenditure_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='pay_date',
            field=models.DateField(),
        ),
    ]
